### ISSUE TITLE
New files?

### ISSUE THREAD

**Issue by braco** [mazemax/import-glob-loader#1]
Thanks for this package @mazemax! I'm using it.

Question: how can we pick up new files? Adding new files that would be picked up by the glob requires restarting webpack currently.

I guess it's the same as the parent project
https://github.com/Aintaer/import-glob-loader/issues/4

**Comment by mazemax** [comment]
You are welcome. Haven't looked into this for a while. Most likely I will need to rewrite it from scratch to implement this feature.
